### ISSUE TITLE
Map, flatMap, and flatten should work on a single layer only

### ISSUE THREAD

**Issue by esorf** [stuartervine/OCTotallyLazy#20]
The expectation for map and flatMap is that they pass each element of the _first_ level sequence to the function. Similarly, flatten needs to work on just _one_ level.

What is currently implemented is interesting, but non-standard. The current map descends a tree of Mappables returning the same structure with the function applied to all non-mappable items. Maybe it should be called ```deepMap```. (And if it were implemented, it should have a mechanism for reconstituting the actual type of sequences in the returned data structure. In the example below, Group objects came back as basic Sequence objects.)

As an example of why this is simply broken, the first thing I needed from OCTotallyLazy was to 
````
    NSArray *groups = [dataArray groupBy:groupingFn];
    NSArray *nodes = [groups map:^MyNodeType(Group *g) {
        // Make a node based on the property of the group
        return node;
    }];
````
Of course it didn't work, because Group is a Sequence which is Mappable. So instead of getting called with the groups I know to be in ```groups```, my mapping function got called with all the items in each of my groups.

**Comment by stuartervine** [comment]
I have no idea why I made map lift mappables... but thanks for fixing it, I've merged your pull request.
